steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/mlpt-cloudteam-migration/pneumonia-detector3', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/mlpt-cloudteam-migration/pneumonia-detector3' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'pneumonia-detector-3',
        '--image', 'gcr.io/mlpt-cloudteam-migration/pneumonia-detector3',
        '--region', 'asia-southeast2',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--service-account', 'cloudrun-sa@mlpt-cloudteam-migration.iam.gserviceaccount.com'
      ]

images:
  - 'asia-southeast2-docker.pkg.dev/mlpt-cloudteam-migration/pneumonia-detector3'